version: 0.0
os: linux
files:
  - source: backend.zip
    destination: /home/ubuntu/schedulemaker/
hooks:
  AfterInstall:
    - location: start.sh
      timeout: 300
      runas: root
#   ApplicationStop:
#     - location: scripts/stop.sh
#       timeout: 300
#       runas: root

