version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
    pre_build:
        commands:
            - npm install --prefix frontend/
    build:
        commands:
            # Frontend
            - npm run build --prefix frontend/
            - aws s3 sync frontend/dist/ s3://schedule-maker-front-end --delete
            # Backend
            - zip -r backend.zip backend/
artifacts:
    files:
        - backend.zip
    name:
        backendZip