# Generated by Django 3.0.5 on 2020-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200512_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
